$engine: 3
$onesync: on
name: Howdy! Core
description: Base resources to run a minimal RedM server with Howdy! framework.

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  # Clean CFX resources
  - action: remove_path
    path: ./resources/[cfx-default]/[gamemodes]
  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/[examples]
  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat
  - action: remove_path
    path: ./resources/[cfx-default]/[local]
  - action: remove_path
    path: ./resources/[cfx-default]/[managers]
  - action: remove_path
    path: ./resources/[cfx-default]/[system]/baseevents
  - action: remove_path
    path: ./resources/[cfx-default]/[system]/rconlog
  - action: remove_path
    path: ./resources/[cfx-default]/[system]/runcode
  - action: remove_path
    path: ./resources/[cfx-default]/[system]/sessionmanager
  - action: remove_path
    path: ./resources/[cfx-default]/[test]

  # Download and prepare server.cfg
  - action: download_github
    src: https://github.com/howdy-rdr/recipes
    ref: main
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg
  - action: move_path
    src: ./tmp/recipe/secrets.cfg
    dest: ./secrets.cfg
  - action: replace_string
    file: ./secrets.cfg
    mode: all_vars

  - action: move_path
    src: ./tmp/recipe/howdyLogo.png
    dest: ./howdyLogo.png

  # Download Howdy! resources & dependencies
  - action: connect_database

  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/oxmysql.zip

  # Cleanup
  - action: remove_path
    path: ./tmp